data_source postgres_docker:
  type: postgres
  connection:
    host: postgres         # Host para uso INTERNO no Airflow/Docker Compose (funciona no Docker)
    port: 5432
    database: airflow      # Corrigido para 'airflow', onde as tabelas GOLD estão.
    username: daxlog123
    password: daxlog123

data_source postgres_local:
  type: postgres
  connection:
    host: localhost        # Host para uso EXTERNO no Terminal/VS Code (funciona no seu PC)
    port: 5432
    database: airflow      # Corrigido para 'airflow', onde as tabelas GOLD estão.
    username: daxlog123
    password: daxlog123
