data_source postgres_daxlog:
  type: postgres
  connection:
    host: postgres          # POSTGRES_HOST (nome do servi√ßo no docker-compose)
    port: 5432              # POSTGRES_PORT
    database: airflow       # POSTGRES_DB
    username: daxlog123     # POSTGRES_USER
    password: daxlog123     # POSTGRES_PASSWORD
